import type { Metadata } from "next";
import { Inter, Roboto, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import "./responsive.css";
import './fontawesome.css'

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
});

	
const barlowCondensed = Barlow_Condensed({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ['latin'],
  variable: '--font-barlow-condensed',	
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${barlowCondensed.variable}`}>
        <>
          {children}
        </>
      </body>
    </html>
  );
}
